package mr

//
// RPC definitions.
//
// remember to capitalize all names.
//

import (
	"os"
	"strconv"
)

//
// example to show how to declare the arguments
// and reply for an RPC.
//

type ExampleArgs struct {
	X int
}

type ExampleReply struct {
	Y int
}

// Heartbeat

type HeartbeatArgs struct {
	WorkerID int
}

type HeartbeatReply struct {
	Alive bool
}

// Add your RPC definitions here.
// TaskType represents the kind of work a worker should do.
type TaskType int

const (
	TaskTypeNone TaskType = iota
	TaskTypeMap
	TaskTypeReduce
	TaskTypeWait
	TaskTypeExit
)

// Pengfei: I unified the RPCs for requesting tasks and reporting task completion
// Request a task / report task completion
type TaskRequestArgs struct{
	WorkerID 		int			// Identify the worker
	WorkerAddress 	string		// IP:port Address 
	TaskID 			int     	// Task ID being reported (if any)
	TaskType 		TaskType	// Task Type being reported (if any)
}

// Generated by the coordinator in response to a TaskRequestArgs
type TaskRequestReply struct {
	WorkerID 				int    				// Assigned Worker ID
	TaskType 				TaskType 
	TaskID   				int
	FileName 				string
	NReduce 				int
	NMap     				int
	IntermediateLocations 	map[int]string	// Map from reduce task ID to list of intermediate file locations
	IsDone   				bool 				// Indicate if all tasks are done
}

// Cook up a unique-ish UNIX-domain socket name
// in /var/tmp, for the coordinator.
// Can't use the current directory since
// Athena AFS doesn't support UNIX-domain sockets.

/**
 *	Author: Pengfei Li
 *	Add distributed mode to the basic MapReduce framework.
 *  By setting env varible "MR_COORDINATOR" to the coordinator's IP address and port,
 *  the worker can connect to the coordinator in distributed mode.
 *  If the env variable is not set, the worker will fall back to the original local mode."
**/

func coordinatorSock() string {
	// for distributed mode
	if addr := os.Getenv("MR_COORDINATOR"); addr != "" {
		return addr
	}

	// for local mode
	s := "/var/tmp/5840-mr-"
    s += strconv.Itoa(os.Getuid())
    return s
}

func IsDistributed() bool {
	return os.Getenv("MR_COORDINATOR") != ""
}
